### ISSUE TITLE
Syntax highlighting completely broken on ST4

### ISSUE THREAD

**Issue by fredrikekre** [JuliaEditorSupport/Julia-sublime#103]
For me syntax highlighting seems completely broken after upgrading to ST4. I removed the package and re-added but no luck. Here is an example (docstrings are highlighted as comments, macros are borked, function keyword doesn't highlight as it should etc.):
<img width="246" alt="Screenshot 2021-05-30 at 15 21 52" src="https://user-images.githubusercontent.com/11698744/120105799-cddd9380-c15a-11eb-89a7-dada597f8da1.png">

System information:
 - Sublime Text 4 (Build 4107)
 - macOS 10.14.6
 - Julia-sublime v1.0.4

**Comment by ric-cioffi** [comment]
Broken here as well. Another example is multi-line comments using `#= =#`. These are particularly nasty because they can break all highlighting past that point.

![image](https://user-images.githubusercontent.com/24350113/120184143-ef995200-c210-11eb-98c7-d3b8a3eb1c5c.png)

System info:
- Sublime Text 4 (Build 4107)
- macOS 10.15.2
- Julia-sublime v1.0.4

**Comment by PetrKryslUCSD** [comment]
When I currently have the julia package on my system, how do I find out its version? it is not shown doing "package list".

**Comment by ric-cioffi** [comment]
> When I currently have the julia package on my system, how do I find out its version? it is not shown doing "package list".

Weird, it does show it to me (sorry for the very unreadable blue):
![image](https://user-images.githubusercontent.com/24350113/120357593-e8a03b80-c305-11eb-8631-294f5654fd56.png)

I can also see it if I try to remove it

**Comment by PetrKryslUCSD** [comment]
![image](https://user-images.githubusercontent.com/9855832/120357871-c0d7b600-c2ba-11eb-8080-17479525732c.png)

**Comment by PetrKryslUCSD** [comment]
The changes relative to my version are relatively few:
![image](https://user-images.githubusercontent.com/9855832/120364160-bff65280-c2c1-11eb-8c1a-c880c7f2e7e0.png)

**Comment by PetrKryslUCSD** [comment]
The highlighting works fine for me on windows with the latest ST. But the multi-line comment is broken:
![image](https://user-images.githubusercontent.com/9855832/120364632-5aef2c80-c2c2-11eb-99ae-a92f639f85e1.png)

**Comment by PetrKryslUCSD** [comment]
Highlighting works well in vscode. I wonder if the syntax definitions could be fruitfully compared in order to track down the problem?

**Comment by jwortmann** [comment]
The syntax definition seems correct to me for the screenshot in the first post and the highlighting style follows the conventions that are used e.g. for Python files, i.e. docstrings are intended to be highlighted as comments and the token scoping for macros are comparable to what is used for Python decorators. The strange highlighting for the `function` keyword is a side effect resulting from a workaround in the new Sublime Text version to preserve the original style for such declaration keywords, because their token scope was in many syntaxes changed from `storage.type.function` (blue italic in Monokai) to `keyword.declaration.function` (red in Monokai). You will see the same style if you open a file of another builtin language. I agree that this is quite unfortunate here, because of the potential side effect for third party languages like Julia which already used the `keyword` scope for `function` before, and it isn't really documented.

The best workaround for now seems to customize the color scheme via *Preferences > Customize Color Scheme* from the menu, for example with the following rules:
```jsonc
{
    "rules":
    [
        {
            "scope": "source.julia keyword.declaration",
            "foreground": "var(red2)",
            "font_style": ""
        },
        {
            "scope": "comment.block.documentation.julia", // if you really want docstrings with the same color as normal strings
            "foreground": "var(yellow)"
        },
        {
            "scope": "punctuation.definition.macro, variable.macro.julia", // arbitrary macros
            "foreground": "var(blue)"
        },
        {
            "scope": "support.function.macro.julia", // built-in macros
            "foreground": "var(blue)",
            "font_style": "italic"
        },
    ]
}
```

In general you can use *Tools > Developer > Show Scope Name* to see the scope at the current cursor position if you'd like to tweak more things.

The broken multi-line comments within function arguments *do* seem like bug to me. @randy3k might wanna take a look at this and can probably fix it easily, otherwise I can give it a try on the next weekend or so. But the other issue reported in #101 seems much more severe to me and I'm probably not familiar enough with this syntax definition here to easily fix that one.

@PetrKryslUCSD The *No description provided / unknown version* is usually shown for pacakges that are not installed via Package Control, but exist as loose folders in the *Packages* directory. I'm not sure whether that applies to portable installations as well though.

**Comment by fredrikekre** [comment]
Frankly, I think this new default looks horrible compared to the old highlighting.

Thanks for the workaround suggestions, I guess I have to play around with those then...

**Comment by JackDunnNZ** [comment]
For what it's worth, I'm also not a fan of the new defaults at all, I think the look before and what VS Code has (and even GitHub's highlighting as limited as it is) is much nicer.

There also do seem to be other problems with the new syntax and defaults, here is an example with the default sublime color scheme with a random file in [Pkg.jl](https://github.com/JuliaLang/Pkg.jl/blob/master/src/Operations.jl) that has big changes to how it was before

![image](https://user-images.githubusercontent.com/4717044/120489493-acacbb00-c385-11eb-9e7d-0522b498b17a.png)

- In the `find_installed` arguments, only the first type is highlighted differently
- some of the functions are italicised and others are not 
- only `Union` in type in the second function is highlighted, but not the contents

I think these are because the types and functions are being highlighted differently depending on whether they are builtin or not, but that doesn't seem like a desirable default (to me at least). I would expect the default highlighting to be based on the semantic/syntactic meaning of the code, not whether or not it's a builtin type/function.

I also pulled a struct definition:

![image](https://user-images.githubusercontent.com/4717044/120492118-ca7b1f80-c387-11eb-985e-cb260c5c0694.png)

Here again the non-builtin types are being highlighted differently, which makes it look pretty weird. There is also a problem with the `repo::GitRepo` line, as when I inspect the scope, both `repo` and `GitRepo` seem to have the same scope

```
source.julia
meta.group.julia
meta.struct.julia
metal.generic-name.julia
```

Which would seemingly make it impossible to highlight `GitRepo` the same way as the other types, even with the overrides/customizations?

If it ends up being necessary to get back to how it was before by using customizations, then I guess that will have to do, but then that seems to be blocked in the type definition above by the two elements having the same scope, which is perhaps a bug?

**Comment by randy3k** [comment]
@JackDunnNZ 
Just added a scope of `meta.type.julia` for identifiers after `::`.

The new syntax has fixed a number of bugs in the original syntax, I don't really recommend switching back to the old syntax. The new syntax is more consistent and comprehensive than the old one. I believe it is just a matter of time to get used to the new syntax. 

With that said, I don't think we should blame the new syntax for doing the highlighting job "incorrectly". The syntax provides scopes to the color scheme to do the job. So the combination of the syntax and color scheme should take the blame. And as @jwortmann pointed out, you could always override the default color scheme to achieve what you want (and it was not possible with the original syntax).

**Comment by jwortmann** [comment]
The mentioned differences for built-in and user-defined functions and types are intended, and I would say they give a nice feedback for example to spot typos easier. In general I think that this syntax has a quite high quality and follows the latest conventions, but if people don't like the default style and find it worse than the highlighting in VS Code, then perhaps there is indeed still some room for improvements. For example I never liked the `meta.generic-name` scope from the Python syntax much, because the `meta` scopes are not colored at all by default. Some other syntaxes use `support.type` for all type names (or `support.class` for the more OOP languages), which probably isn't optimal either, but this is something without a clear convention in the guidelines.

Randy, what do you think about changing the scopes for built-in types to `support.type.builtin.julia` and for other types back to just `support.type.julia`? That would highlight all types the same by default in most (all?) color schemes, but if users want, they can still customize the style only for the built-in (or not built-in) types to distinguish them. It should be doable by matching identifiers with an uppercase first letter as a heuristic for the user-defined types.

There is also currently a discussion (which I've linked somewhere above) to modify the Monokai scheme to bring back some of the original styles that were - more or less accidentally - changed in Sublime Text 4. This could theoretically be done here as well to fix the highlighting for the `function` and some other keywords in Monokai, but I'm unsure if this is the best way to do it and probably wouldn't recommend it at this time.

**Comment by randy3k** [comment]
> It should be doable by matching identifiers with an uppercase first letter as a heuristic for the user-defined types.

Current master branch assigns `meta.type` to the `Foo` as in `x::Foo` while an alone `Foo` will still receive `meta.generic-name`. Using an uppercase first letter as a heuristic to match both of them seems inevitably creating some edge cases. For example, it is common to use a single uppercase letter to define a matrix.
```
M = [1 2; 3 4]
```

My experience tells me that users do not like the highlight not because of the syntax scopes, but rather a bad interaction between the syntax and the color scheme. Customizing the color scheme should improve 99% of the use case.

**Comment by matthieugomez** [comment]
Is syntax highlighting with multi-line comments fixed on master? If so, could you release a new version?
