### ISSUE TITLE
improper highlighting for commented functions (when space is missing)

### ISSUE THREAD

**Issue by ahwillia** [JuliaEditorSupport/Julia-sublime#13]
<img width="116" alt="screen shot 2016-08-07 at 1 42 19 pm" src="https://cloud.githubusercontent.com/assets/636625/17465160/faf7790a-5ca4-11e6-8c83-7fe758d3f1a8.png">

Coming up with descriptive titles is so much harder than pasting an image 😄 .

Thanks for this. I'm terrible with regex, otherwise I'd fix myself.

**Comment by ViktorQvarfordt** [comment]
Thanks for opening issues! Yeah, the images are really helpful :)

When I took over the project there were many issues with regards to correctly highlighting unicode symbols as parts of keywords. There's been some partial fixes for this, but these fixes sometimes introduce issues like the one you just found. And I'm sure there's more, which is why I've started working on doing it right once for all. I'll have a commit for this in a day or so when I get time.
