### ISSUE TITLE
Inconsistent highlighting for parametric functions vs types/immutables

### ISSUE THREAD

**Issue by ahwillia** [JuliaEditorSupport/Julia-sublime#17]
Here's another small nitpick. In general, things are looking pretty beautiful though!

<img width="182" alt="screen shot 2016-08-08 at 11 09 37 pm" src="https://cloud.githubusercontent.com/assets/636625/17506399/66bb3366-5dbd-11e6-9d40-0cadd01b8dd5.png">

**Comment by ViktorQvarfordt** [comment]
Indeed, this has been annoying me as well. I already have some local changes for this. However, some things need to be discussed:

(The numbers in what follow refer to the text in the images below.)

- Color of `<:`? An inconsistency is made clear in 3. I see no obvious solution. Making the `<:` red inside a type breaks the flow and looks really confusing.
- Since types are used a lot, and function calls by default have the same color as types. I'm considering making it so that functions do not get highlighted by the default theme. This is how essentially any other language behaves. Not sure why the choice was made to make functions blue originally.
- Default color of macros? It is very blue in 5. If functions are no longer blue, should macros still be? I like the idea of giving one color to types exclusively. Macros white, or some other color?

What do you think?

*Previous syntax version, default color*
![old-syntax-orig-color](https://cloud.githubusercontent.com/assets/344809/17512710/7a701126-5e29-11e6-804b-a21c69b34f2c.png)

*Suggested new version, default color*
![new-syntax-orig-color](https://cloud.githubusercontent.com/assets/344809/17512714/7fb12ddc-5e29-11e6-9797-d4418d4a4ea8.png)

*Suggested new version, using my custom color theme to show difference*
![new-syntax-alt-color](https://cloud.githubusercontent.com/assets/344809/17512720/8322dd76-5e29-11e6-883e-0039eed61c3a.png)

A file that uses many "edge cases" is (multidimensional.jl)[https://github.com/JuliaLang/julia/blob/master/base/multidimensional.jl#L23]. It does not look too good in the current state. With my current changes line 23 becomes
![example](https://cloud.githubusercontent.com/assets/344809/17513054/115055be-5e2b-11e6-9b26-c918016ca0b7.png)

**Comment by ahwillia** [comment]
:+1: for your custom color scheme. I like orange for macros. Maybe something slightly different than the sea green for function calls? Maybe keep the function calls blue (which is a pleasing color) and make the parametric types sea green (which is slightly less pleasing, but will probably appear less often this way?).

Anyways, I like the underlying logic - so you should go for it once your happy. Also don't forget `typealias`!

<img width="250" alt="screen shot 2016-08-09 at 11 37 13 am" src="https://cloud.githubusercontent.com/assets/636625/17528898/09ed630c-5e26-11e6-9800-b2a942f5a2a2.png">

**Comment by ViktorQvarfordt** [comment]
Regarding the colors: A syntax highlighting package only sets scopes, colors are determined from the scope by the color scheme. Type annotations have scope `support.type` which is blue in the default color scheme, ordinary functions have scope `variable.function` which is not colorized in the default color scheme.

This package currently breaks convention by setting scope `support.function` for all function calls, this scope is only intended for built-in functions (such as `map`, `filter`, `range`). This is how it should be done.

I will try to adhere to conventions as much as possible (comparing with built-in languages such as c, python, javascript).

I'm currently rewriting some things that where a mess, a fix for these things will be part of that.

**Comment by ViktorQvarfordt** [comment]
Fixed in #21.
