### ISSUE TITLE
How to handle highlighting Modules?

### ISSUE THREAD

**Issue by ahwillia** [JuliaEditorSupport/Julia-sublime#19]
I also added this to the wiki:

<img width="164" alt="screen shot 2016-08-09 at 7 13 04 pm" src="https://cloud.githubusercontent.com/assets/636625/17539728/56993f70-5e65-11e6-9051-b53f2c037538.png">

I think it would make sense for `MyModule` to inherit the same color as `MyType`/`myfunc` in these examples. When you are overloading an imported function, everything looks 👍 to me -- we want something similar for the examples above:

<img width="268" alt="screen shot 2016-08-09 at 7 16 04 pm" src="https://cloud.githubusercontent.com/assets/636625/17539782/e385e8e8-5e65-11e6-8f16-975fde673293.png">

**Comment by ViktorQvarfordt** [comment]
Great! Had not thought about this. First highlighted line: We definitely want all of `MyModule.MyType` to be highlighted as a type. However, when calling or defining `MyModule.myfunc`, don't you think that only the function should be highlighted (as a function call/blue or new function/green)?

**Comment by ahwillia** [comment]
I sort of think of `MyModule.whatever` as a single unit, and hence think the same color would work well. I guess I don't feel super strongly as long as it is consistent for a function call and definition.

**Comment by ViktorQvarfordt** [comment]
I tend to think of `MyModule.whatever` as separate entities :) Clearly this is largely personal preference. Therefore will try to follow convention on as much as possible. After looking at other languages (built-ins like c, python, javascript), the convention is to set the scope of the module/type/object containing the function as `variable.other` and the function itself as `variable.function` for function calls. Redefining functions in modules is not common in other languages, but as you say this should behave the same to the choice for function calls. 

I'm currently rewriting some things that where a mess, a fix for these things will be part of that.

Note that all function calls except the core `Base` exported functions will become white. Because I will attempt to follow sublime convention, this is how all other languages behave, it feels weird to deviate from this. Scream loudly you think this is bad. Note that all function calls will get the scope `variable.function`, so that they can be colorized in a custom color scheme.

**Comment by ViktorQvarfordt** [comment]
A lot has happened and stuff have been fixed. Pave a look in #21 and see what you think. If you're up to it it would be great if you could use `develop` for some days and see if it's okay. Note that the tests cover all issues that have been opened (and the tests are passing :))

**Comment by ahwillia** [comment]
Happy to try it out -- I'm not too familiar with Sublime's package system. How would I checkout the development branch?

**Comment by ViktorQvarfordt** [comment]
Assuming Linux (otherwise other path): Sublime packages are put in `~/.config/sublime-text-3/Packages/`, I guess you will see Julia or Julia-sublime in there. You'd need to remove that, to not confuse package control you should remove (uninstall or deactivate) via Package Control from within sublime. Then, into the Packages folder, do

```
$ git clone https://github.com/JuliaEditorSupport/Julia-sublime.git
$ git checkout develop
```
opening the `syntax_test_julia.jl` would be a good way to see the new highlighting, the most interesting things happen at lines starting with 234, function definitions.

**Comment by ahwillia** [comment]
Is the Mac equivalent path `/Users/alex/Library/Application Support/Sublime Text 3/Packages/User`? This doesn't look right...

Do you know if it would be possible to alter Package Control settings to follow `develop` rather than `master`? https://packagecontrol.io/docs/settings

**Comment by ViktorQvarfordt** [comment]
Yeah that's right, but don't go into user, one level up. You can also get to the package dir by cmd-shift-P --> Browse Packages

Unfortunately package control cannot be configured to change branch.

**Comment by ahwillia** [comment]
> Unfortunately package control cannot be configured to change branch.

That's pretty lame.

I'm not seeing a Julia folder... Just this weird `bz2` folder.

<img width="468" alt="screen shot 2016-08-11 at 12 57 16 pm" src="https://cloud.githubusercontent.com/assets/636625/17602828/358b3522-5fc3-11e6-8150-50d5e02ee148.png">

**Comment by ViktorQvarfordt** [comment]
Ah, my bad: Package control installs packages into `/Users/.../Library/Application Support/Sublime Text 3/Installed Packages/` But you should not touch those files. Do cmd+shift+p remove package instead

**Comment by ahwillia** [comment]
Ok - I did that and then added this repository through package manager... But I can't seem to set syntax highlighting to Julia... Do I need to activate it or something?

The relevant bit of my `Package Control.sublime-settings` file now looks like:

```
	"installed_packages":
	[
		"Package Control",
		"UnicodeMath"
	],
	"repositories":
	[
		"https://github.com/JuliaEditorSupport/Julia-sublime"
	]
```

**Comment by ViktorQvarfordt** [comment]
You cannot manually in this way via package control. "repositories" refers to a special type of config file, like the default package control repository https://github.com/wbond/package_control_channel/tree/master/repository

Manual git clone (or just zip download) would be easiest.

**Comment by ViktorQvarfordt** [comment]
I'm on Gitter btw.

**Comment by ahwillia** [comment]
I think the way Modules are highlighted on `develop` looks great.
