### ISSUE TITLE
Highlighing elementwise operators in symbols

### ISSUE THREAD

**Issue by ahwillia** [JuliaEditorSupport/Julia-sublime#22]
This is on the `develop` branch. Seems like the `*` and `/` should be purple:

<img width="162" alt="screen shot 2016-08-12 at 4 06 09 pm" src="https://cloud.githubusercontent.com/assets/636625/17639658/1d5b47c6-60a9-11e6-8533-0c7c98b468bd.png">

**Comment by ViktorQvarfordt** [comment]
Ah you found this :) as you probably saw, currently some work and some don't; ![image](https://cloud.githubusercontent.com/assets/344809/17640773/dc4faba0-6107-11e6-8ac8-22cee7fddd89.png).

There was a line `(\+\+|\.\+|{{symb_op}})| # TODO: Complete this list` hehe

The symbol parsing is slightly more involved than one might first expect. Naively one could parse everything after the `:` until an obvious terminators such as `,\)\]\s`. I don't know if this gives real problems, but ![image](https://cloud.githubusercontent.com/assets/344809/17640826/4edd593c-6109-11e6-9b0c-3ebfa3867865.png) would become ![image](https://cloud.githubusercontent.com/assets/344809/17640835/81555590-6109-11e6-9e98-9d05b6dd50e4.png) which is simply wrong because only `.` is part of the symbol as seen by:

```julia
julia> :.a
ERROR: MethodError: no method matching *(::Symbol, ::Int64)
```

So, I started digging in [julia-parser.scm](https://github.com/JuliaLang/julia/blob/master/src/julia-parser.scm) and extracted the allowed multi-character-operator and currently I have this
![image](https://cloud.githubusercontent.com/assets/344809/17641004/70cc442c-610e-11e6-8b99-36bc6fcc0aa0.png)

This is pushed to develop. Play with it and see if it behaves as expected.

**Comment by ahwillia** [comment]
Didn't realize this was how the parser handles this! Looks good!  👍 

I think this can be closed? Feel free to reopen if you aren't happy with it yet.
