### ISSUE TITLE
Comments not matching correct

### ISSUE THREAD

**Issue by fredrikekre** [JuliaEditorSupport/Julia-sublime#27]
Similar as in #13, doesn't match a comment without the space in between (for both line comment and block comment), see picture on line 7-8, 13-15. I tried to fix it and make a PR but scratching my head why [this](https://github.com/JuliaEditorSupport/Julia-sublime/blob/master/Julia.sublime-syntax#L97) is not capturing the case on line 7-8.
![comment](https://cloud.githubusercontent.com/assets/11698744/17845249/cf331502-6840-11e6-8789-658048b871f0.png)

**Comment by ViktorQvarfordt** [comment]
Thanks for this! Silly that something so similar to #13 managed to sneak in again. I've fixed and added tests.

The regex for general variables was eating `#` as well. Fixed by adding `#` to [this line](https://github.com/JuliaEditorSupport/Julia-sublime/commit/f5190414e2b5e0ba53538489cb2673954a5a358b#diff-ab08e5c4d116882e2903d91dee204081R23). You might ask, why am often parsing "everything except ...", it is because there more allowed symbols than disallowed ones, because of unicode.

**Comment by ViktorQvarfordt** [comment]
Above mentioned line defines a regex variable that is then used to define [this](https://github.com/JuliaEditorSupport/Julia-sublime/blob/master/Julia.sublime-syntax#L26) regex variable that is then used a lot, most relevant to this case it is used at [this](https://github.com/JuliaEditorSupport/Julia-sublime/blob/master/Julia.sublime-syntax#L282) line.

**Comment by fredrikekre** [comment]
Alright!
