### ISSUE TITLE
Broken highlightning in function definintions

### ISSUE THREAD

**Issue by fredrikekre** [JuliaEditorSupport/Julia-sublime#33]
A picture is worth a thousand words...
![syntax](https://cloud.githubusercontent.com/assets/11698744/18079458/1f9b7e2a-6e91-11e6-993e-21180ff2137e.png)

**Comment by ViktorQvarfordt** [comment]
Partial fix is pushed. However, the last test with line break between input args is difficult because:

- To distinguish function calls `f(x)` from assignment form declarations `f(x) = ...` we must\* use regex lookaheads.
- In https://www.sublimetext.com/docs/3/syntax.html under the subsection "Match Patterns" it says "Regexes are only ever run against a single line of text at a time."

I.e. the lookahead cannot look ahead of line breaks.

\* I see no other option than regex lookaheads for "jumping back" in the parsing. If not using lookaheads, we would parse `f(x)` not knowing what comes after, if this is followed by `=` we must jump back and change the assigned scopes, but I see no way of doing this.

We are not the only ones with this issue, the following is javascript:

![image](https://cloud.githubusercontent.com/assets/344809/18085185/53677d58-6eaa-11e6-92f0-9af6dabab512.png)

Note that this is a default sublime package, and it uses lookaheads just we do for Julia-sublime.

**Comment by fredrikekre** [comment]
Okay. Could it be possible to keep track of it in the same way as e.g. a multi line string?

**Comment by ViktorQvarfordt** [comment]
Unfortunately, no. The difference is that when the syntax parser encounters `"` it knows that a string begins, nothing that follows after can change this fact. However, when the syntax parser encounters `f(` it cannot know if this is part of a function call or a function declaration. What follows after is of importance and there is no way to back-track. (...Other than using lookaheads, which have the single-line limitation due to how sublime text handles syntax parsing. The reason that sublime parses syntaxes line-by-line is for performance; when editing a 1000+ line document, one doesn't want the syntax parser to re-parse the entire file, only the line(s) being edited).

**Comment by fredrikekre** [comment]
Okay, well, maybe this shouldn't be viewed as an issue with this package then.

**Comment by ViktorQvarfordt** [comment]
You're right. Given that there seems to be no possible way of solving this, I close this now. If more information comes to light in the future, we can reopen this.
