### ISSUE TITLE
Forces tab_size to be 4

### ISSUE THREAD

**Issue by djsegal** [JuliaEditorSupport/Julia-sublime#63]
Seems a little aggressive to overpower user's desire to use 2 space width

**Comment by ViktorQvarfordt** [comment]
Do you refer to the setting https://github.com/JuliaEditorSupport/Julia-sublime/blob/master/Julia.sublime-settings ? Just configure it to whatever you want locally.

The config is there because the Julia community uses 4 spaces for indentation. The purpose of this plugin is to facilitate writing code in Julia. This includes helping you to follow conventions.

If you disagree with my reasoning, please present an argument for your case :)

**Comment by djsegal** [comment]
I think your settings clobber user defined ones though :(

**Comment by ViktorQvarfordt** [comment]
Do you mean that the package settings take precedence over user settings? If so, do you know if it is possible to have package settings that are applied only if there are no corresponding user settings?

**Comment by djsegal** [comment]
That's what I mean.

And I have no clue :(

**Comment by djsegal** [comment]
Any word on this? Don't even know where to look for something like this

**Comment by djsegal** [comment]
@ViktorQvarfordt these are the only docs I can find about sublime text preference load order:

+ https://www.sublimetext.com/docs/3/settings.html

--------

If it's not possible to adjust it's priority now, can we remove this feature?

It's keeping me from adopting the package (and doesn't seem essential because Julia ignores whitespace)

// I understand the docs say 4 spaces, but they also say no underscores

**Comment by ViktorQvarfordt** [comment]
I agree :) Fixed in the above commit.

**Comment by djsegal** [comment]
Thank you! :)

Have a happy new year!
