### ISSUE TITLE
Can you share font name from screenshot?

### ISSUE THREAD

**Issue by tackgyulee** [JuliaEditorSupport/Julia-sublime#68]
I know it's unrelated post but couldn't help asking, can you share the name of the font you're using in screenshot from README.md? I'd really appreciate if you do.

![screenshot](https://github.com/JuliaEditorSupport/Julia-sublime/raw/master/highlight-example.png)

**Comment by ViktorQvarfordt** [comment]
I took that screenshot a while ago, but I'm quite certain that the font is
DejaVu Sans Mono. If it looks slightly different on your system, it might
be because I have tweaked the font hinting on my system (xububtu).

On Dec 19, 2017 04:26, "tackgyulee" <notifications@github.com> wrote:

I know it's unrelated post but couldn't help asking, can you share the name
of the font you're using in screenshot from README.md? I'd really
appreciate if you do.

[image: screenshot]
<https://github.com/JuliaEditorSupport/Julia-sublime/raw/master/highlight-example.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/JuliaEditorSupport/Julia-sublime/issues/68>, or mute
the thread

**Comment by tackgyulee** [comment]
Yeah it seems right and beautiful. Thanks for sharing!
